### ISSUE TITLE
hardcoded library version: 6.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by mhayen** [jlolling/talendcomp_maven_plugins#4]
Hi Jan,

Our CI/CD checks of the talend jobs using your components, currently fail on the 6.0.0-SNAPSHOT version which is used for the components packaged dependencies.
This is at least the case with the talendcomp_tContextInput and talendcomp_tJobInstance.
Is there a reason for hard-coding this version?
Can it be a non SNAPSHOT version?

Thank you
Mark

**Comment by jlolling** [comment]
Hi Mark,

Talend actually expected the libraries with such a strange version and artIfactId. I can of course allow to put the libraries in the normal way to the maven repo.
I will check if the components will work if the library is placed in the normal style.

Best regards
Jan
.
